left:
  prefix: /left_jaka_driver
  name: left
right:
  prefix: /right_jaka_driver
  name: right
motion:
  default_joint_vel: 2.0
  default_joint_acc: 1.2
  jog_joint_step_rad: 0.03
  default_both_joint_sync_mode: same
  right_joint_sign_same_physical:
  - -1
  - 1
  - 1
  - 1
  - 1
  - -1
  right_tcp_base_sign_same_physical:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  right_tcp_tool_sign_same_physical:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  left_joint_sign_same_physical:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  left_tcp_base_sign_same_physical:
  - -1
  - -1
  - 1
  - -1
  - -1
  - 1
  left_tcp_tool_sign_same_physical:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  sync_joint_move_enabled: true
  sync_min_duration: 0.15
  sync_min_joint_vel: 0.05
  sync_min_joint_acc: 0.05
  sync_delta_epsilon: 0.0003
safety:
  require_power_on: true
  require_servo_on: true
  require_no_collision: true
home:
  left:
  - 3.139835119247436
  - 0.42971023917198187
  - -0.5666612982749939
  - 0.0020004832185804857
  - 0.16700118780136108
  - 1.5059341192245483
  right:
  - -0.00013079980271866136
  - 2.710859060287475
  - 0.5616226792335509
  - 0.0016140391817316437
  - 2.981350898742676
  - 1.5074795484542847
