#!/usr/bin/env python3
import argparse
import csv
import json
import math
import re
import time
import urllib.error
import urllib.request
from pathlib import Path


def parse_delta(text):
    parts = [x.strip() for x in text.split(",")]
    if len(parts) != 6:
        raise ValueError("--delta must have 6 values: dx,dy,dz,drx,dry,drz")
    return [float(x) for x in parts]


def safe_name(text):
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", text.strip())
    return text.strip("_") or "moveset"


def post_json(url, payload, timeout=30):
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as e:
        raise RuntimeError(f"Cannot connect to backend: {url}\n{e}") from e


def rad_to_deg_list(values):
    return [float(math.degrees(x)) for x in values]


def fmt_num(x, digits=6):
    if isinstance(x, int):
        return str(x)
    return f"{float(x):.{digits}f}".rstrip("0").rstrip(".")


def fmt_array(values, digits=6):
    return "[" + ",".join(fmt_num(x, digits) for x in values) + "]"


def write_csv(path, rows, side):
    fieldnames = [
        "segment_index",
        "j1_deg", "j2_deg", "j3_deg", "j4_deg", "j5_deg", "j6_deg",
        "source",
        "note",
    ]
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            q = row[f"{side}_joint_deg"]
            writer.writerow({
                "segment_index": row["segment_index"],
                "j1_deg": q[0],
                "j2_deg": q[1],
                "j3_deg": q[2],
                "j4_deg": q[3],
                "j5_deg": q[4],
                "j6_deg": q[5],
                "source": "D35.7 dry_run segmented IK",
                "note": "absolute joint target in degree",
            })


def write_tcpip_jsonl(path, rows, side, speed_deg_s, acc_deg_s):
    with path.open("w") as f:
        for row in rows:
            q = row[f"{side}_joint_deg"]
            cmd = {
                "cmdName": "joint_move",
                "relFlag": 0,
                "jointPosition": q,
                "speed": speed_deg_s,
                "accel": acc_deg_s,
            }
            f.write(json.dumps(cmd, ensure_ascii=False) + "\n")


def write_jks(path, rows, side, moveset_name, speed_deg_s, acc_deg_s):
    title = f"{moveset_name}_{side}"
    with path.open("w") as f:
        f.write(f"# Generated by dual_arm_app D40.1 exporter\n")
        f.write(f"# Program: {title}\n")
        f.write(f"# Side: {side}\n")
        f.write(f"# Source: D35.7 dry_run segmented IK\n")
        f.write(f"# WARNING: Review in JAKA Software before running on real robot.\n")
        f.write(f"# Joint arrays are absolute joint targets in degree.\n")
        f.write(f"# IO placeholders below are comments. Edit pin numbers before use.\n\n")

        f.write(f"# Example IO placeholders:\n")
        f.write(f"# set_digital_output(0,0,1,1)  # basic DO0 ON immediately\n")
        f.write(f"# wait_input(0,1,1,3)          # wait basic DI1 ON for 3 sec\n\n")

        for row in rows:
            idx = int(row["segment_index"])
            q = row[f"{side}_joint_deg"]
            var = f"q_{idx:03d}"
            f.write(f"{var} = {fmt_array(q, 6)}\n")
            f.write(f"movj({var},0,{fmt_num(speed_deg_s, 3)},{fmt_num(acc_deg_s, 3)},0)\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", default="Test1", help="Object name in dual_arm_app")
    ap.add_argument("--moveset", default="demo_z20", help="Export moveset name")
    ap.add_argument("--delta", default="0,0,20,0,0,0", help="dx,dy,dz,drx,dry,drz")
    ap.add_argument("--backend", default="http://localhost:8000", help="Backend base URL")
    ap.add_argument("--speed-scale", type=float, default=0.05)
    ap.add_argument("--max-translation-mm", type=float, default=100.0)
    ap.add_argument("--max-rotation-rad", type=float, default=0.5)
    ap.add_argument("--max-segment-translation-mm", type=float, default=10.0)
    ap.add_argument("--max-segment-rotation-rad", type=float, default=0.026)
    ap.add_argument("--max-segment-tcp-rotation-rad", type=float, default=0.12)
    ap.add_argument("--jks-speed-deg-s", type=float, default=10.0)
    ap.add_argument("--jks-acc-deg-s2", type=float, default=60.0)
    ap.add_argument("--outdir", default="dual_arm_app/exports")
    args = ap.parse_args()

    moveset_name = safe_name(args.moveset)
    delta = parse_delta(args.delta)

    payload = {
        "name": args.name,
        "target_delta": delta,
        "dry_run": True,
        "max_translation_mm": args.max_translation_mm,
        "max_rotation_rad": args.max_rotation_rad,
        "max_segment_translation_mm": args.max_segment_translation_mm,
        "max_segment_rotation_rad": args.max_segment_rotation_rad,
        "max_segment_tcp_rotation_rad": args.max_segment_tcp_rotation_rad,
        "speed_scale": args.speed_scale,
    }

    url = args.backend.rstrip("/") + "/api/object/execute_calibrated_world_rigid_large"
    plan = post_json(url, payload)

    if not plan.get("ok"):
        print(json.dumps(plan, indent=2, ensure_ascii=False))
        raise SystemExit("[ERROR] Dry-run failed. Export aborted. No motion was sent.")

    segments = plan.get("segments") or plan.get("plan", {}).get("segments") or []
    if not segments:
        raise SystemExit("[ERROR] Dry-run has no segments. Export aborted.")

    rows = []
    for seg in segments:
        left = seg.get("left_target_joint")
        right = seg.get("right_target_joint")
        if not isinstance(left, list) or len(left) != 6:
            raise SystemExit(f"[ERROR] segment {seg.get('segment_index')} missing left_target_joint")
        if not isinstance(right, list) or len(right) != 6:
            raise SystemExit(f"[ERROR] segment {seg.get('segment_index')} missing right_target_joint")

        rows.append({
            "segment_index": int(seg["segment_index"]),
            "left_joint_rad": [float(x) for x in left],
            "right_joint_rad": [float(x) for x in right],
            "left_joint_deg": rad_to_deg_list(left),
            "right_joint_deg": rad_to_deg_list(right),
            "left_target_tcp_world": seg.get("left_target_tcp_world"),
            "right_target_tcp_world": seg.get("right_target_tcp_world"),
            "target_object_pose_world": seg.get("target_object_pose_world"),
        })

    stamp = time.strftime("%Y%m%d_%H%M%S")
    outdir = Path(args.outdir) / f"{moveset_name}_{stamp}"
    outdir.mkdir(parents=True, exist_ok=True)

    meta = {
        "ok": True,
        "moveset": moveset_name,
        "object": args.name,
        "target_delta": delta,
        "segment_count": len(rows),
        "source": "D35.7 dry_run execute_calibrated_world_rigid_large",
        "warning": [
            "This export was generated from dry-run only.",
            "Running the .jks files in JAKA Software can move the real robot.",
            "Left and right files are independent; simultaneous synchronization is not guaranteed without an external start/handshake mechanism.",
            "Review speed, acceleration, tool, user frame, payload, IO mapping, and workspace clearance before running.",
        ],
        "jks_speed_deg_s": args.jks_speed_deg_s,
        "jks_acc_deg_s2": args.jks_acc_deg_s2,
        "request": payload,
        "plan_summary": {
            "mode": plan.get("mode"),
            "segment_count": plan.get("segment_count"),
            "segment_delta": plan.get("segment_delta"),
            "summary": plan.get("summary"),
            "warnings": plan.get("warnings"),
        },
        "steps": rows,
    }

    (outdir / "plan_raw.json").write_text(json.dumps(plan, indent=2, ensure_ascii=False))
    (outdir / "moveset_both.json").write_text(json.dumps(meta, indent=2, ensure_ascii=False))

    write_csv(outdir / "left_waypoints_deg.csv", rows, "left")
    write_csv(outdir / "right_waypoints_deg.csv", rows, "right")

    write_jks(outdir / "left_jaka_program.jks", rows, "left", moveset_name, args.jks_speed_deg_s, args.jks_acc_deg_s2)
    write_jks(outdir / "right_jaka_program.jks", rows, "right", moveset_name, args.jks_speed_deg_s, args.jks_acc_deg_s2)

    write_tcpip_jsonl(outdir / "left_tcpip_joint_move.jsonl", rows, "left", args.jks_speed_deg_s, args.jks_acc_deg_s2)
    write_tcpip_jsonl(outdir / "right_tcpip_joint_move.jsonl", rows, "right", args.jks_speed_deg_s, args.jks_acc_deg_s2)

    readme = f"""D40.1 Moveset Export

Moveset: {moveset_name}
Object: {args.name}
Target delta: {delta}
Segments: {len(rows)}

Generated files:
- moveset_both.json          Full neutral moveset data for both arms
- plan_raw.json              Raw D35.7 dry-run response
- left_waypoints_deg.csv     Left arm joint targets in degree
- right_waypoints_deg.csv    Right arm joint targets in degree
- left_jaka_program.jks      JAKA Script draft for left arm
- right_jaka_program.jks     JAKA Script draft for right arm
- left_tcpip_joint_move.jsonl  TCP/IP command-list draft for left arm
- right_tcpip_joint_move.jsonl TCP/IP command-list draft for right arm

Important:
1. These files were generated from dry-run only.
2. Running .jks files in JAKA Software can move the real robot.
3. Joint targets were converted from radian to degree for JAKA Script.
4. Left/right programs are independent. They do NOT guarantee dual-arm synchronization by themselves.
5. For a real cooperative lift, add a start handshake/interlock via IO before running both arms.
6. Review tool frame, user frame, payload, speed, acceleration, IO mapping, and workspace clearance.
"""
    (outdir / "README_IMPORT.txt").write_text(readme)

    print("[OK] Export completed")
    print(f"[OUTDIR] {outdir}")
    print(f"[SEGMENTS] {len(rows)}")
    print("")
    print("Files:")
    for path in sorted(outdir.iterdir()):
        print(" -", path)


if __name__ == "__main__":
    main()
